---
driver:
  name: dokken
  chef_version: 14.12.9

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
suites:
  - name: default
    data_bags_path: "../../data_bags"
    encrypted_data_bag_secret_key_path: "../../.my_secret"
    run_list:
      - recipe[users::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

